# Generated by Django 2.2 on 2021-05-04 23:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'colores',
            },
        ),
        migrations.CreateModel(
            name='Cristal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio_costo_sin_iva', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('precio_venta_con_iva', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'verbose_name_plural': 'cristales',
            },
        ),
        migrations.CreateModel(
            name='FormaDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Formas De Pago',
            },
        ),
        migrations.CreateModel(
            name='GrupoPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Obra_Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Obras Sociales',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('domicilio', models.CharField(blank=True, max_length=50)),
                ('edad', models.SmallIntegerField(blank=True, null=True)),
                ('telefono', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cuit', models.CharField(blank=True, max_length=20)),
                ('iva', models.CharField(blank=True, choices=[('RI', 'Responsable Inscripto')], max_length=2)),
                ('sexo', models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=2)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.Localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Multifocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos Multifocal',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[^$)]+$', "No puede contener '$' ni ')'.")])),
                ('precio_costo_sin_iva', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('precio_venta_con_iva', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, default='', max_length=254)),
                ('fecha_inicio', models.DateField(auto_now_add=True, null=True)),
                ('fecha_entrega', models.DateTimeField()),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seña', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.CharField(blank=True, default='0', max_length=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('estado_de_pago', models.CharField(blank=True, choices=[('Seña', 'Parcialmente Pagado'), ('Total', 'Completamente Pagado')], default='Seña', max_length=5)),
                ('forma_de_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.FormaDePago')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loptique.Persona')),
            ],
            options={
                'verbose_name_plural': 'Doctores',
            },
            bases=('loptique.persona',),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loptique.Persona')),
                ('obra_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.Obra_Social')),
            ],
            bases=('loptique.persona',),
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=254)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('seña', models.BooleanField(default=False)),
                ('egreso', models.BooleanField(default=False)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.Venta')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=50)),
                ('nombre', models.CharField(blank=True, default='', max_length=50)),
                ('cbu', models.CharField(blank=True, default='', max_length=50)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.Banco')),
            ],
            options={
                'verbose_name_plural': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_patilla', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[^$)]+$', "No puede contener '$' ni ')'.")])),
                ('modelo', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[^$)]+$', "No puede contener '$' ni ')'.")])),
                ('stock_actual', models.SmallIntegerField(blank=True, default=0)),
                ('comprometido', models.SmallIntegerField(blank=True, default=0)),
                ('precio_costo_sin_iva', models.SmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('precio_venta_con_iva', models.SmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.GrupoProducto')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.Marca')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.Proveedor')),
                ('rubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.Rubro')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('precio_costo_sin_iva', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('precio_venta_con_iva', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.Proveedor')),
            ],
            options={
                'verbose_name_plural': 'materiales',
            },
        ),
        migrations.AddField(
            model_name='marca',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.Proveedor'),
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('cuotas', models.SmallIntegerField()),
                ('recargo', models.SmallIntegerField()),
                ('retencion', models.SmallIntegerField()),
                ('forma_de_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.FormaDePago')),
            ],
        ),
        migrations.CreateModel(
            name='Anteojo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_esfera', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('od_cilindro', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('od_eje', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('oi_esfera', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('oi_cilindro', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('oi_eje', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('distancia_interpupilar', models.CharField(blank=True, default=0, max_length=10)),
                ('precio_lente', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('descuento_lente', models.CharField(blank=True, default='0', max_length=10)),
                ('precio_final_lente', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('precio_armazon', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('descuento_armazon', models.CharField(blank=True, default='0', max_length=10)),
                ('precio_final_armazon', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('precio_tratamientos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('descuento_tratamientos', models.CharField(blank=True, default='0', max_length=10)),
                ('precio_final_tratamientos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('armazon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.Producto')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.Color')),
                ('tipo_lente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.Cristal')),
                ('tratamientos', models.ManyToManyField(blank=True, to='loptique.Tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Venta_varios',
            fields=[
                ('venta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loptique.Venta')),
                ('productos', models.ManyToManyField(to='loptique.Producto')),
            ],
            options={
                'verbose_name_plural': 'Ventas Varios',
            },
            bases=('loptique.venta',),
        ),
        migrations.AddField(
            model_name='venta',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.Paciente'),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('venta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loptique.Venta')),
                ('laboratorio', models.CharField(blank=True, default='', max_length=50)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.Doctor')),
            ],
            bases=('loptique.venta',),
        ),
        migrations.CreateModel(
            name='Multifocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('di_lejos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('di_cerca', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('descuento', models.CharField(blank=True, default='0', max_length=10)),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tipo_multifocal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.Tipo_Multifocal')),
                ('receta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loptique.Receta')),
            ],
            options={
                'verbose_name_plural': 'multifocales',
            },
        ),
        migrations.CreateModel(
            name='AnteojoLejos',
            fields=[
                ('anteojo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loptique.Anteojo')),
                ('receta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loptique.Receta')),
            ],
            options={
                'verbose_name_plural': 'Anteojos Lejos',
            },
            bases=('loptique.anteojo',),
        ),
        migrations.CreateModel(
            name='AnteojoCerca',
            fields=[
                ('anteojo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loptique.Anteojo')),
                ('receta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loptique.Receta')),
            ],
            options={
                'verbose_name_plural': 'Anteojos Cerca',
            },
            bases=('loptique.anteojo',),
        ),
    ]
