# Generated by Django 2.2 on 2021-05-04 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorAnteojo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'colores',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='codigo_patilla',
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.Color'),
        ),
        migrations.AlterField(
            model_name='anteojo',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loptique.ColorAnteojo'),
        ),
    ]
