# Generated by Django 2.2 on 2021-05-04 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0003_auto_20210504_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_costo_sin_iva',
            new_name='precio_contado',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio_venta_con_iva',
            new_name='precio_de_lista',
        ),
    ]
