# Generated by Django 2.2 on 2021-02-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0003_auto_20210202_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado_de_pago',
            field=models.CharField(blank=True, choices=[('Seña', 'Parcialmente Pagado'), ('Total', 'Completamente Pagado')], default='Seña', max_length=5),
        ),
    ]
