# Generated by Django 2.2 on 2021-05-05 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0004_auto_20210504_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[^$)]+$', "No puede contener '$' ni ')'.")]),
        ),
    ]
