# Generated by Django 2.2 on 2021-05-05 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0005_auto_20210505_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[^$)]+$', "No puede contener '$' ni ')'.")]),
        ),
    ]
