# Generated by Django 2.2 on 2021-02-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0006_auto_20210202_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='isSeña',
            field=models.BooleanField(default=False),
        ),
    ]
