# Generated by Django 2.2 on 2021-02-04 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0007_ingreso_isseña'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cristal',
            options={'verbose_name_plural': 'cristales'},
        ),
    ]
