# Generated by Django 2.2 on 2021-02-04 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0009_auto_20210203_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name_plural': 'Doctores'},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'verbose_name_plural': 'Localidades'},
        ),
    ]
