# Generated by Django 2.2 on 2021-02-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0011_auto_20210204_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
