# Generated by Django 2.2 on 2021-02-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0012_persona_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='comprometido',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
