# Generated by Django 2.2 on 2021-02-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0013_auto_20210204_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cbu',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
