# Generated by Django 2.2 on 2021-02-04 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0014_auto_20210204_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='isSeña',
            new_name='seña',
        ),
    ]
