# Generated by Django 2.2 on 2021-02-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0016_auto_20210205_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anteojo',
            name='precio_armazon',
        ),
        migrations.RemoveField(
            model_name='anteojo',
            name='precio_tratamientos',
        ),
    ]
