# Generated by Django 2.2 on 2021-02-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0017_auto_20210205_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anteojo',
            name='precio_final_armazon',
        ),
        migrations.RemoveField(
            model_name='anteojo',
            name='precio_final_tratamientos',
        ),
    ]
