# Generated by Django 2.2 on 2021-02-07 20:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0024_auto_20210207_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armazon',
            name='precio_costo_sin_iva',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='armazon',
            name='precio_venta_con_iva',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='cristal',
            name='precio_costo_sin_iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='cristal',
            name='precio_venta_con_iva',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='material',
            name='precio_costo_sin_iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='material',
            name='precio_venta_con_iva',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_costo_sin_iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta_con_iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='precio_costo_sin_iva',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='precio_venta_con_iva',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
