# Generated by Django 2.2 on 2021-02-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0025_auto_20210207_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multifocal',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
