# Generated by Django 2.2 on 2021-02-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0028_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multifocal',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='multifocal',
            name='di_cerca',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='multifocal',
            name='di_lejos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
