# Generated by Django 2.2 on 2021-02-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0030_auto_20210208_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteojo',
            name='descuento_armazon',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='anteojo',
            name='descuento_lente',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='anteojo',
            name='descuento_tratamientos',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='multifocal',
            name='descuento',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
    ]
