# Generated by Django 2.2 on 2021-02-09 02:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0031_auto_20210208_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_costo_sin_iva',
            field=models.SmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta_con_iva',
            field=models.SmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
