# Generated by Django 2.2 on 2021-02-09 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0035_auto_20210209_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[^$)]', "No puede contener '$' ni ')'.")]),
        ),
    ]
