# Generated by Django 2.2 on 2021-02-09 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loptique', '0039_auto_20210209_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armazon',
            name='descripcion',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[^$)]+$', "No puede contener '$' ni ')'.")]),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='descripcion',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[^$)]+$', "No puede contener '$' ni ')'.")]),
        ),
    ]
